# 0. Numpy
NumPy is Python's library that facilitates processing matrices or generally large multidimensional arrays. In addition to the data structure, NumPy provides efficiently implemented features for numerical computation.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,5,7,9,11]) # numpy 배열 생성
arr1

array([ 1,  2,  3,  5,  7,  9, 11])

In [3]:
type(arr1) # ndarray : N-dimensional Array

numpy.ndarray

In [4]:
arr1.shape # .shape : 데이터의 차원 출력 (1차원)

(7,)

In [5]:
arr1.size # .size : 데이터의 갯수 출력

7

In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape # 2차원

(2, 4)

In [8]:
arr2.size

8

### Numpy Method
> np.full(n, a) : n개의 데이터를 a로 채움 

> np.zeros(n) : n개의 데이터를 0으로 채움

> np.ones(n) : n개의 데이터를 1로 채움

> np.random.randint(a, b) : a~b 사이의 정수를 받아옴

> np.random.random(n) : 0~1사이의 실수 n개를 받아옴

> np.arange(n, m, s) : n부터 m-1까지 간격이 s인 값들이 담긴 배열 생성

In [9]:
arr1 = np.full(6,2) # 6개의 데이터를 2로 채움
arr1

array([2, 2, 2, 2, 2, 2])

In [10]:
arr2 = np.zeros([2, 6]) # 2행 6열의 데이터를 0으로 채움
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr2 = np.zeros([2, 6], dtype = int) # 데이터 타입 설정 가능
arr2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [13]:
arr4 = np.random.randint(1, 100)
arr4

12

In [14]:
arr5 = np.random.random(5)
arr5

array([0.39094682, 0.83631124, 0.08953148, 0.72589487, 0.98647734])

In [15]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1 = np.arange(5)
arr2 = np.arange(5, 10)

## Numpy 연산
기본적으로 numpy배열의 연산은 각 행과 열에 대응되는 숫자끼리 연산을 수행한다.

In [17]:
arr1

array([0, 1, 2, 3, 4])

In [18]:
arr2

array([5, 6, 7, 8, 9])

In [19]:
arr1 + arr2

array([ 5,  7,  9, 11, 13])

In [20]:
arr2 - arr1

array([5, 5, 5, 5, 5])

In [21]:
arr1 * arr2

array([ 0,  6, 14, 24, 36])

In [22]:
arr1 / arr2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [23]:
arr2 > arr1

array([ True,  True,  True,  True,  True])

## Numpy 통계값

In [24]:
arr1 = np.array([13,2,6,5,12,3,5,1,5])
arr1

array([13,  2,  6,  5, 12,  3,  5,  1,  5])

In [25]:
arr1.max() # 최댓값

13

In [26]:
arr1.min() # 최솟값

1

In [27]:
arr1.mean() # 평균값

5.777777777777778

In [28]:
arr1.std() # 표준편차

3.9094693523909294

In [29]:
arr1.var() # 분산

15.283950617283953

In [30]:
np.median(arr1) # 중앙값

5.0